---
title: "Practical 4 - Spatial data types"
execute:
  freeze: auto
format: 
  html:
    body-classes: no-banner
  PrettyPDF-pdf:
    keep-tex: false
    number-sections: true
embed-resources: true
editor_options: 
  chunk_output_type: console
---

```{r}
#| echo: false
#| message: false
#| warning: false
#| purl: false
#| results: hide
#| eval: true
library(webexercises)
knitr::purl("day2_practical_4.qmd")
```

<font size="5"> **Aim of this practical:** </font>

1.  Work with different types of spatial data types including: Areal, Geostatistical and Spatial Point process data.

2.  Read and visualize shapefiles into R

3.  Manipulate and visualize `sf` spatial object in R

4.  Manipulate and visualize raster data in R.

::: supplementary
You can download the R-script of this practical by clicking the button below:

<br>

{{< downloadthis day2_practical_4.R dname="practical_4.R" label="Download Practical 3 R script" icon="database-fill-down" type="success" >}}

:::

```{r child="practicals/spatial_data_types_areal.qmd"}
```

```{r child="practicals/spatial_data_types_geostats.qmd"}
```

```{r child="practicals/spatial_data_types_points.qmd"}
```
