---
title: "Practical 6 - Spatio temporal models and model comparison"
execute: 
  freeze: auto
format: 
  html:
    body-classes: no-banner
  PrettyPDF-pdf:
    keep-tex: true
    number-sections: true
embed-resources: true
editor_options: 
  chunk_output_type: console
---

```{r}
#| echo: false
#| message: false
#| warning: false
#| purl: false
#| results: hide

library(webexercises)
knitr::purl("day4_practical_6.qmd")
```

<font size="5"> **Aim of this practical:** </font>

In this practical we are going to look at space-time model and model comparison and validation techniques.

::: supplementary
You can download the R-script of this practical by clicking the button below:

{{< downloadthis day4_practical_6.R dname="day4_practical_6.R" label="Download Practical 6 R script" icon="database-fill-down" type="success" >}}

:::

## Space time models

```{r child="practicals/space_time_ex.qmd"}
```

## Model check and comparison

```{r child="practicals/LM_resids.qmd"}
```

```{r child="practicals/GLM_scores_ex.qmd"}
```
