---
title: "Spatio-temporal models with `inlabru`"
subtitle: "15–18 September 2026 • Dodoma, Tanzania<br>Jafet Belmont · Sara Martino · Janine Illian"
title-block-banner: "#00000000"
title-block-banner-color: "white"
format:
  html:
    css: styles.css
    body-classes: home-page
  PrettyPDF-pdf:
    keep-tex:  true
    number-sections: true
editor_options: 
  chunk_output_type: console
---


# Welcome to the course!

-   Welcome to the `inlabru` workshop in Dodoma!
-   The aim of this workshop is to introduce you to a range of statistical modelling approaches, and how temporal, spatial and spatio-temporal models can be fitted using  the `inlabru` package.
-   Workshop materials are available in the github repository.

::: {.callout-warning}
##  Important! ⚠️

 Please use the instructions provided [here](Install_software.qmd) to install and check your installation
  *before* the course starts.
:::

# Learning Objectives for the workshop

At the end of the workshop, participants will have an understanding of:

-   the motivation for and the challenges of analysing and modelling spatial data
-   statistical models used to analyse spatial and spatio-temporal data
-   the implementation of these models in the `inlabru` package
-   how to independently analyse spatial data with `inlabru`

# Intended audience

The workshop aims to cater for participants with a range of different backgrounds, who are interested in analysing data with modern spatial and spatio-temporal statistical modelling approaches.

# Prerequisites

Participants should be familiar with the `R` environment, and general statistical approaches for modelling such as regression, analysis of (co)variance, and generalized linear models.

No knowledge of `R-INLA` or `inlabru` is required.

# Schedule {#schedule-tabs}



::: panel-tabset
### Tuesday 15$^{th}$ 

: {.striped .hover}


| Time | Topic |
|:----------------------------------:|:----------------------------------:|
| 9:00 - 9:30   | [**Welcome  and  introduction to the course**](slides/welcome.html)  |
| 9:30 - 10:30  | [**Session 1**: Introduction to `inlabru`](slides/slides_1.html)  |
| 10:30 - 10:45 | Coffee break ☕ | 
| 10:45 - 12:00 | [Practical Session 1](practicals/LMM_ex.qmd)                    |
| 12:00 - 13:00 | [**Session 2**: The `inlabru` workflow](slides/slides_2.html)   |
| 13:00 - 14:30 |  Lunch 🍽️ |
| 14:30 - 15:30 | [Practical Session 2](practicals/GLMM_fit.qmd) |
| 15:30 - 15:45 | Coffee break ☕ |
| 15:45  - 17:00 | [**Session 3**: Time Series Models](slides/slides_3.html)|


### Wednesday 16$^{th}$ 

: {.striped .hover}


| Time | Topic |
|:----------------------------------:|:----------------------------------:|
| 9:00 - 10:30 | [Practical Session 3](day2_practical_3.html) |
| 10:30 - 11:00 | Coffee break ☕ |
| 11:00 - 12:00 | [**Session 4**: Introduction to Spatial Statistics](slides/slides_intro_spatial.html) |
| 12:00 - 13:00 |  [Practical Session 4](day2_practical_4.html) |
| 13:00 - 14:30 | Lunch 🍽️ |

###	Thursday 17$^{th}$

: {.striped .hover}

| Time | Topic |
|:----------------------------------:|:----------------------------------:|
| 11:00 - 12:00 | [**Session 5**: Areal processes](slides/slides_areal.html) |
| 12:00 - 1:00 |  [**Session 6**: Geostatistics](slides/slides_geostats.html) |
| 13:00 - 14:30 | Lunch 🍽️ |
| 14:30 - 15:50 | [**Session 7**: Point Processes](slides/slides_points.html) |
| 15:30 - 17:00 |  [Practical Session 5](day3_practical_5.html)| |

### Friday 18$^{nd}$

: {.striped .hover}


| Time | Topic |
|:----------------------------------:|:----------------------------------:|
| 09:00 - 10:00 | [**Session 8**: Spatiotemporal models](slides/slides_spatioTemporal.qmd)  |
| 10:00 - 11:00 |  [**Session 9**: Model comparison and evaluation](slides/slides_Model_Comparison.qmd) |
| 11:00 - 12:00 | Coffee break ☕ |
| 12:00 - 13:00 |  [Practical Session 6](day4_practical_6.qmd) |
| 13:00 - 14:30 | Lunch 🍽️ |
| 14:40 - 15:30 | [**Session 10**: Multi-likelihood/joint likelihood models](slides/slides_multilik.html)  |
| 15:30 - 16:00 | [Closing session](slides/slides_Closing_Remarks.html) and discussion|
| 16:00- 17:00  | [Practical Session 7 &  General practice](day4_practical_7.qmd) |


:::


# Licence
[CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/)


# Citation


```{=html}
<div class="modal fade" id="cite-info" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Citation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <pre><code class="language-bibtex">@Manual{Belmont2026inlabru,
  title  = {inlabruCourseMarch2026: Course Materials for Pamplona inlabru Course 19-22 October 2026},
  author = {Belmont, Jafet and Martino, Sara and Illian, Janine},
  year   = {2026},
  url    = {https://inlabru-courses.github.io/Pamplona2026/}
}</code></pre>
      </div>
    </div>
  </div>
</div>

```

<button type="button" class="venue-info-link" data-bs-toggle="modal" data-bs-target="#cite-info">
::: venue-card
Belmont J., Martino S., Illian, J. F (2026). _inlabru Course October 2026: Course Materials for Pamplona inlabru 19-22 October 2026_.
https://inlabru-courses.github.io/Pamplona2026/
:::
</button>




# Contact {#sec-contact}

Questions about the workshop? Join the discussion on [GitHub Discussions space](https://github.com/inlabru-courses/Pamplona2026/discussions)
